### ISSUE TITLE
Episode #17

### ISSUE THREAD

**Issue by benjaminreid** [benjaminreid/bitpodcast.com#11]
- Questions
  - Game of the year
- Mandrill
- PlayStation Experience trailers (Metal Gear, The Order, Uncharted, No Mans Sky)
- Driveclub

**Comment by daviddarnes** [comment]
- Game of the year
  - [Grand Theft Auto V](https://www.youtube.com/watch?v=hBvMSP7cI-Q), on PlayStation 4
  - [Velocity 2X](https://www.youtube.com/watch?v=MQjt3CUaoqU)
- [Mandrill](http://mandrill.com/)
- PlayStation Experience trailers
  - [Metal Gear Online](https://www.youtube.com/watch?v=61cqE53jbOc)
  - [The Order](https://www.youtube.com/watch?v=pFyoHXLu3zM)
  - [Uncharted 4](https://www.youtube.com/watch?v=Ow2cL-pp6p8)
  - Latest [No Man's Sky gameplay trailer](https://www.youtube.com/watch?v=nmwG6Sj1Yfg)
  - [Interview with Sean Murray](https://www.youtube.com/watch?v=h-kifCYToAU), founder of Hello Games, about No Man's Sky
