### ISSUE TITLE
Archive legacy site repo

### ISSUE THREAD

**Issue by daviddarnes** [benjaminreid/bitpodcast.com#13]
Remember the old Anchor CMS repo? https://github.com/nouveller/bitpodcast

Maybe we should merge this into an archive or legacy branch of the current repo? Then we have it on archive, plus we can delete the old one. Might be nicer way to track the sites history too. Would it work if you fork the initial commit of the master branch and then do a pull request from the old one into that branch? Then it's sort of in order.

**Comment by daviddarnes** [comment]
As discussed, delete (or archive in some manner) old BitPodcast repo: https://github.com/nouveller/bitpodcast

**Comment by daviddarnes** [comment]
@nouveller I'm considering deleting the old repo entirely. None of the changes are of use to us and we transferred all of the design changes to the new Jekyll site. The new site, and workflow to go with it, is working really well. What do you think?

**Comment by benjaminreid** [comment]
Yep, agreed

**Comment by daviddarnes** [comment]
@nouveller cool, well it's under your account so…
![doit](https://cloud.githubusercontent.com/assets/1177460/9982192/1f69f998-5fcb-11e5-816e-f898853e5639.gif)

**Comment by benjaminreid** [comment]
Excellent gif. Deleted!

:bomb: :boom: 

![](https://media.giphy.com/media/NPbCChOYWo4aA/giphy.gif)
