### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by benjaminreid** [benjaminreid/bitpodcast.com#46]
Thoughts on some new branding @daviddarnes?

I've added a "proper" code font. http://codepen.io/nouveller/pen/PPaZjR

**Comment by daviddarnes** [comment]
@nouveller Looks like a great type choice to me. Though to be devils advocate, how about Roboto Mono? Not sure if it looks better, but considering it's one of Google's flagship fonts it might be a good choice? Here's a sample http://codepen.io/daviddarnes/pen/jbpaJa

**Comment by benjaminreid** [comment]
@daviddarnes "Here's a sample", music to my ears. :notes:

That looks _way_ better. 

:heart:

**Comment by benjaminreid** [comment]
Putting these here for reference.

## Inconsolata

![screen shot 2015-11-03 at 09 15 22](https://cloud.githubusercontent.com/assets/713128/10904483/6fe08ec0-820b-11e5-93fe-a34445f95345.png)

## Roboto Mono

![screen shot 2015-11-03 at 09 15 01](https://cloud.githubusercontent.com/assets/713128/10904484/6fe57d54-820b-11e5-8625-e4998a615e34.png)

**Comment by benjaminreid** [comment]
P.S. This is a nice resource. http://programmingfonts.org/

**Comment by daviddarnes** [comment]
How about Source Code Pro? I updated the sample with it, easier than forking http://codepen.io/daviddarnes/pen/jbpaJa

Image sample for ref:
![source-code-pro](https://cloud.githubusercontent.com/assets/1177460/10905123/1c3d33f4-8210-11e5-832e-f8c3022c49f8.png)

**Comment by benjaminreid** [comment]
Definitely like Roboto the best. :smile:

**Comment by daviddarnes** [comment]
@nouveller :+1: for Roboto Mono too, plus we get the Google benefits if they start adding special features.

**Comment by daviddarnes** [comment]
@nouveller :eyes: 
![bitpodcast-redesign](https://cloud.githubusercontent.com/assets/1177460/14235266/e44b1ba6-f9f0-11e5-9f35-fe5faeeea8e7.png)

**Comment by benjaminreid** [comment]
@daviddarnes :heart_eyes: Like this a lot.
