### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by benjaminreid** [benjaminreid/bitpodcast.com#52]
Thought I'd add this so I don't forget, plan to try fit it in tonight if I can.

@daviddarnes Mind chucking in the list to the sound effects you found please? I forgot where they were :cry:

**Comment by daviddarnes** [comment]
- clever girl
- Now!
- Metal gear?
- Great Scott!
- Intro
- Outro

**Comment by benjaminreid** [comment]
:tada:
